### ISSUE TITLE
Couldn't run the example command

### ISSUE THREAD

**Issue by jink1994** [ai-systems/DILP-Core#25]
Traceback (most recent call last):
  File "/Users/jessejing/DILP-Core/run.py", line 55, in <module>
    B, pred_f, constants_f = process_file('%s/facts.dilp' % sys.argv[1])
  File "/Users/jessejing/DILP-Core/run.py", line 46, in process_file
    terms = [Term(False, term) for term in result['arguments'][idx]]
  File "/Users/jessejing/miniforge3/envs/dilp/lib/python3.9/site-packages/pyparsing/results.py", line 193, in __getitem__
    return self._toklist[i]
IndexError: list index out of range

Although I didn't install the python 3.6 as indicated in the dockerfile, the error seems not related to this, can you tried to recreate this error?

**Comment by youssefmahmoud89** [comment]
Has anyone been able to fix this error yet?

**Comment by youssefmahmoud89** [comment]
I have been able to run the example and the python-notebook tests. I had to do the following:
(Tested it on an M1 mac and an intel Mac as well)

1) You need anaconda installed.

2) You need to create a conda virtual environment by:
`conda create -n myenv python=3.6`

3) Activate your environment and install the packages required in requirements.txt through conda install or pip install (For tensorflow `conda install tensorflow` worked in my case and for ray `pip install ray` worked)

4) You need to install pyparsing version 2.4.6:
`pip install pyparsing==2.4.6`

5) Run the example by executing:
`python run.py examples/even`

6) to run the untitled.ipynb test you need to change 
`tf.enable_eager_execution()` to `tf.compat.v1.enable_eager_execution()`
